import os

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect, text

from clio_agent_graph.workflows.reporting.matching.models import IssueRetrievalRequest
from clio_agent_graph.workflows.reporting.normalization.models import ErrorSignals, NormalizedReport
from clio_agent_graph.workflows.reporting.retrieval.models import BugIndexInput, IndexStatus
from clio_agent_graph.workflows.reporting.retrieval.postgres import PostgresRetrievalRepository
from clio_agent_graph.workflows.reporting.retrieval.query import (
    build_search_query,
    build_search_text,
    calculate_document_hash,
)

pytestmark = pytest.mark.postgres


@pytest.fixture(scope="module")
def postgres_url():
    if os.getenv("CLIO_RUN_POSTGRES_TESTS") != "1":
        pytest.skip("Set CLIO_RUN_POSTGRES_TESTS=1 to run PostgreSQL integration tests.")

    from testcontainers.community.postgres import PostgresContainer

    with PostgresContainer("pgvector/pgvector:pg16", driver="psycopg") as postgres:
        yield postgres.get_connection_url(driver="psycopg")


@pytest.fixture(scope="module")
def migrated_database(postgres_url, monkeypatch_module):
    engine = create_engine(postgres_url)
    with engine.begin() as connection:
        connection.execute(
            text(
                """
                CREATE TABLE projects (id bigint PRIMARY KEY);
                CREATE TABLE bugs (
                    id bigint PRIMARY KEY,
                    project_id bigint NOT NULL REFERENCES projects(id),
                    title varchar(200) NOT NULL,
                    description text,
                    source varchar(50) NOT NULL,
                    error_type varchar(255),
                    message text,
                    stack_trace jsonb NOT NULL DEFAULT '[]',
                    raw_payload jsonb,
                    occurred_at timestamptz NOT NULL
                );
                CREATE TABLE issues (
                    id bigint PRIMARY KEY,
                    project_id bigint NOT NULL REFERENCES projects(id),
                    title varchar(200) NOT NULL,
                    summary text,
                    status varchar(30) NOT NULL
                );
                CREATE TABLE issue_bugs (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    issue_id bigint NOT NULL REFERENCES issues(id),
                    bug_id bigint NOT NULL REFERENCES bugs(id),
                    UNIQUE(issue_id, bug_id)
                );
                CREATE TABLE bug_embeddings (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    bug_id bigint NOT NULL REFERENCES bugs(id),
                    embedding real[],
                    embedding_model varchar(200),
                    embedding_dimension integer,
                    embedded_at timestamptz
                );
                """
            )
        )
    monkeypatch_module.setenv("CLIO_DATABASE_URL", postgres_url)
    command.upgrade(Config("alembic.ini"), "head")
    yield engine
    engine.dispose()


@pytest.fixture(scope="module")
def monkeypatch_module():
    from pytest import MonkeyPatch

    patch = MonkeyPatch()
    yield patch
    patch.undo()


def _report(report_id: int, observed: str, code: str) -> NormalizedReport:
    return NormalizedReport(
        bug_report_id=report_id,
        observed_behavior=observed,
        error_signals=ErrorSignals(
            error_type="PaymentException",
            message="Internal Server Error",
            error_codes=[code],
            stack_frames=["PaymentService.approve"],
        ),
    )


def test_migration_preserves_legacy_table_and_runs_hybrid_sql(migrated_database, postgres_url):
    inspector = inspect(migrated_database)
    assert "legacy_bug_embeddings" in inspector.get_table_names()
    assert "bug_retrieval_documents" in inspector.get_table_names()
    assert "bug_embeddings" in inspector.get_table_names()

    with migrated_database.begin() as connection:
        connection.execute(text("INSERT INTO projects(id) VALUES (3)"))
        connection.execute(
            text(
                """
                INSERT INTO bugs(
                    id, project_id, title, source, error_type, message,
                    stack_trace, raw_payload, occurred_at
                ) VALUES
                    (72, 3, '현재 결제 오류', 'API',
                     'PaymentException', 'PAY-500', '["PaymentService.approve"]', '{}',
                     CURRENT_TIMESTAMP),
                    (101, 3, '결제 승인 실패', 'API',
                     'PaymentException', 'PAY-500', '["PaymentService.approve"]', '{}',
                     CURRENT_TIMESTAMP),
                    (102, 3, '결제 처리 오류', 'API',
                     'PaymentException', 'PAY-501', '["PaymentService.approve"]', '{}',
                     CURRENT_TIMESTAMP)
                """
            )
        )
        connection.execute(
            text(
                """
                INSERT INTO issues(id, project_id, title, summary, status) VALUES
                    (19, 3, '결제 승인 실패', '결제 승인 과정에서 오류가 발생한다.', 'CLOSED')
                """
            )
        )
        connection.execute(
            text(
                """
                INSERT INTO issue_bugs(issue_id, bug_id) VALUES (19, 101), (19, 102)
                """
            )
        )

    repository = PostgresRetrievalRepository(postgres_url)
    first_report = _report(101, "결제 승인 시 PAY-500 오류가 발생한다.", "PAY-500")
    second_report = _report(102, "결제 처리 과정에서 PAY-501 오류가 발생한다.", "PAY-501")
    for bug_id, report, embedding in (
        (101, first_report, [1.0, 0.0]),
        (102, second_report, [0.0, 1.0]),
    ):
        search_text = build_search_text(report)
        result = repository.save_index(
            BugIndexInput(project_id=3, bug_id=bug_id, normalized_report=report),
            search_text=search_text,
            document_hash=calculate_document_hash(report, search_text),
            embedding=embedding,
            embedding_model="fake:semantic",
        )
        assert result.status is IndexStatus.CREATED

    current_report = _report(72, "결제 승인 시 PAY-500 오류가 발생한다.", "PAY-500")
    request = IssueRetrievalRequest(
        project_id=3,
        bug_id=72,
        normalized_report=current_report,
    )
    query = build_search_query(request)
    scope = repository.load_scope(
        request,
        embedding_model="fake:semantic",
        embedding_dimension=2,
    )

    assert scope.eligible_bug_count == 2
    assert scope.indexed_bug_count == 2
    assert [hit.bug_id for hit in repository.search_exact(query, scope, limit=50)][0] == 101
    assert 101 in [
        hit.bug_id for hit in repository.search_lexical(query, scope, limit=50, threshold=0.1)
    ]
    vector_hits = repository.search_vector(
        query,
        scope,
        embedding=[1.0, 0.0],
        embedding_model="fake:semantic",
        limit=50,
    )
    assert [hit.bug_id for hit in vector_hits] == [101, 102]
    issues = repository.hydrate_issues(request, [101, 102], issue_limit=20)
    assert len(issues) == 1
    assert issues[0].issue_id == 19
    assert issues[0].status == "CLOSED"
    assert [bug.bug_id for bug in issues[0].bugs] == [101, 102]
